version: '3.8'

services:
  api:
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_SERVER=postgres
      - APP_ENV=prod
    volumes:
      - ./models:/app/models
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4